[package]
name = "bwfs"
version = "0.1.0"
edition = "2021"

[dependencies]
fuser = "0.16.0"
libc = "0.2"
time = "0.3"
image = "0.25.9"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"